### Binary classification problem

In [4]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder

In [3]:
df = pd.read_csv('./breast_cancer_data.csv')
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [6]:
df.shape

(569, 33)

In [7]:
df.drop(columns=['id', 'Unnamed: 32'], inplace=True)

In [8]:
df.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

In [9]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

In [10]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [11]:
X_train

array([[-0.53204843,  0.76086768, -0.57040516, ..., -0.82742301,
         0.2594812 , -0.16655782],
       [-0.8753616 , -0.58385273, -0.86928929, ..., -0.66137821,
         0.09884784, -0.33906772],
       [-0.13198928, -0.03254133, -0.1060232 , ...,  0.3444351 ,
        -0.30116073,  0.174176  ],
       ...,
       [-0.12064008, -0.38969524, -0.17600985, ..., -0.41200802,
        -0.65707387, -0.83248887],
       [-0.16036226, -1.28617551, -0.1418399 , ..., -0.41003851,
         0.20436191, -0.18048719],
       [ 0.1857882 ,  1.12041859,  0.22085559, ...,  0.6580416 ,
         0.60752015,  0.21274964]], shape=(455, 30))

In [12]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [13]:
y_train

array([0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0,
       0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0,
       0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1,
       0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,

In [14]:
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [16]:
X_train_tensor

tensor([[-0.5320,  0.7609, -0.5704,  ..., -0.8274,  0.2595, -0.1666],
        [-0.8754, -0.5839, -0.8693,  ..., -0.6614,  0.0988, -0.3391],
        [-0.1320, -0.0325, -0.1060,  ...,  0.3444, -0.3012,  0.1742],
        ...,
        [-0.1206, -0.3897, -0.1760,  ..., -0.4120, -0.6571, -0.8325],
        [-0.1604, -1.2862, -0.1418,  ..., -0.4100,  0.2044, -0.1805],
        [ 0.1858,  1.1204,  0.2209,  ...,  0.6580,  0.6075,  0.2127]],
       dtype=torch.float64)

### Defining the model

In [28]:
class MySimpleNN():

    def __init__(self, X):
        self.weight = torch.rand(X.shape[1], 1, dtype=torch.float64, requires_grad=True)
        self.bias = torch.zeros(1, dtype=torch.float64, requires_grad=True)

    def forward(self, X):
        z = torch.matmul(X, self.weight) + self.bias
        y_pred = torch.sigmoid(z)
        return y_pred
    
    def loss_function(self, y_pred, y):
        #clamp predictions to avoid log(0)
        epsilon = 1e-7
        y_pred = torch.clamp(y_pred, epsilon, 1 - epsilon)

        #calculate loss
        loss = -(y_train_tensor * torch.log(y_pred) + (1 - y_train_tensor) * torch.log(1 - y_pred)).mean()
        return loss
    

In [18]:
learning_rate = 0.1
epoches = 25

### Training pipelines

In [29]:
#create model
model = MySimpleNN(X_train_tensor)

for epoch in range(epoches):

    #forward pass
    y_pred = model.forward(X_train_tensor)
 

    # loss calculate
    loss = model.loss_function(y_pred, y_train_tensor)

    # backward pass
    loss.backward()

    #parameters update
    with torch.no_grad():
        model.weight -= learning_rate * model.weight.grad
        model.bias -= learning_rate * model.bias.grad


    #zero gradients
    model.weight.grad.zero_()
    model.bias.grad.zero_()

    print(f'Epoch: {epoch + 1}, Loss: {loss.item()}')

Epoch: 1, Loss: 3.404139440355274
Epoch: 2, Loss: 3.2622192697712604
Epoch: 3, Loss: 3.1170195867347554
Epoch: 4, Loss: 2.96965387299934
Epoch: 5, Loss: 2.8213894021973167
Epoch: 6, Loss: 2.6657576249032804
Epoch: 7, Loss: 2.5078082383082574
Epoch: 8, Loss: 2.3478771420003355
Epoch: 9, Loss: 2.1854926797016887
Epoch: 10, Loss: 2.0237475161540353
Epoch: 11, Loss: 1.8617453582533057
Epoch: 12, Loss: 1.7056420417658824
Epoch: 13, Loss: 1.5606151738234404
Epoch: 14, Loss: 1.4284729344229878
Epoch: 15, Loss: 1.3108175968133562
Epoch: 16, Loss: 1.206797516179586
Epoch: 17, Loss: 1.1129349182721935
Epoch: 18, Loss: 1.0359843968206943
Epoch: 19, Loss: 0.9747518527239428
Epoch: 20, Loss: 0.9273026548024882
Epoch: 21, Loss: 0.8912595161657779
Epoch: 22, Loss: 0.8641411797456444
Epoch: 23, Loss: 0.8436598421892463
Epoch: 24, Loss: 0.8279115257719742
Epoch: 25, Loss: 0.8154405191876345


In [32]:
model.bias

tensor([-0.0881], dtype=torch.float64, requires_grad=True)

In [55]:
#model evaluate
with torch.no_grad():
    y_pred = model.forward(X_test_tensor)
    y_pred = (y_pred > 0.1).float()
    accuracy = (y_pred ** y_test_tensor).float().mean()


In [56]:
print(f'Accuracy: {accuracy.item()}')

Accuracy: 0.9973838329315186
