In [2]:
import numpy as np

In [3]:
np.zeros((3,3), dtype=str)

array([['', '', ''],
       ['', '', ''],
       ['', '', '']], dtype='<U1')

In [4]:
np.ones((3,4), dtype=float)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [5]:
np.random.rand(4,5,1)

array([[[0.20758326],
        [0.95099042],
        [0.14695411],
        [0.79392925],
        [0.33219732]],

       [[0.2216282 ],
        [0.74075082],
        [0.66211049],
        [0.31556715],
        [0.19268787]],

       [[0.93753956],
        [0.14684367],
        [0.61802996],
        [0.0491907 ],
        [0.35667419]],

       [[0.19376576],
        [0.15217723],
        [0.0329224 ],
        [0.23778459],
        [0.25057486]]])

In [6]:
b = np.random.randint(10,20,(6,6))
b

array([[10, 12, 13, 15, 14, 16],
       [11, 12, 11, 13, 14, 18],
       [19, 14, 15, 17, 11, 10],
       [13, 19, 15, 13, 15, 11],
       [19, 10, 16, 13, 12, 17],
       [18, 18, 18, 15, 11, 15]], dtype=int32)

In [7]:
b[::-2]

array([[18, 18, 18, 15, 11, 15],
       [13, 19, 15, 13, 15, 11],
       [11, 12, 11, 13, 14, 18]], dtype=int32)

In [8]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [15]:
np.arange(20).reshape(4,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])